name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          scheme: Sperimentare
        run: |
          echo $pwd
          xcodebuild clean build analyze -scheme Sperimentare -project Sperimentare.xcodeproj
