name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          scheme: Sperimentare
        working-directory: Sperimentare
        run: |
          xcodebuild clean build -scheme "Sperimentare (iOS)" -project "Sperimentare.xcodeproj" -sdk iphonesimulator
